/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AccountingRouteImport } from './routes/accounting'
import { Route as BankingRouteImport } from './routes/banking'
import { Route as EndOfDayRouteImport } from './routes/end-of-day'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PayrollRouteImport } from './routes/payroll'
import { Route as PosRouteImport } from './routes/pos'
import { Route as PurchasingRouteImport } from './routes/purchasing'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SalesRouteImport } from './routes/sales'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as AccountingIndexRouteImport } from './routes/accounting.index'
import { Route as AccountingBalanceSheetRouteImport } from './routes/accounting.balance-sheet'
import { Route as AccountingCashFlowRouteImport } from './routes/accounting.cash-flow'
import { Route as AccountingJournalEntriesRouteImport } from './routes/accounting.journal-entries'
import { Route as AccountingLedgerRouteImport } from './routes/accounting.ledger'
import { Route as AccountingProfitLossRouteImport } from './routes/accounting.profit-loss'
import { Route as AccountingTrialBalanceRouteImport } from './routes/accounting.trial-balance'
import { Route as BankingIndexRouteImport } from './routes/banking.index'
import { Route as BankingHistoryRouteImport } from './routes/banking.history'
import { Route as BankingReconcileRouteImport } from './routes/banking.reconcile'
import { Route as CustomerDepositsIndexRouteImport } from './routes/customer-deposits.index'
import { Route as CustomerDepositsDepositIdRouteImport } from './routes/customer-deposits.$depositId'
import { Route as CustomersIndexRouteImport } from './routes/customers.index'
import { Route as CustomersCustomerIdRouteImport } from './routes/customers.$customerId'
import { Route as EndOfDayIndexRouteImport } from './routes/end-of-day.index'
import { Route as EndOfDayDepositsRouteImport } from './routes/end-of-day.deposits'
import { Route as EndOfDayHistoryRouteImport } from './routes/end-of-day.history'
import { Route as ExpensesIndexRouteImport } from './routes/expenses.index'
import { Route as ExpensesExpenseIdRouteImport } from './routes/expenses.$expenseId'
import { Route as InventoryIndexRouteImport } from './routes/inventory.index'
import { Route as PayrollIndexRouteImport } from './routes/payroll.index'
import { Route as PayrollRunIdRouteImport } from './routes/payroll.$runId'
import { Route as PayrollPayConfigRouteImport } from './routes/payroll.pay-config'
import { Route as PayslipsPayslipIdRouteImport } from './routes/payslips.$payslipId'
import { Route as PosIndexRouteImport } from './routes/pos.index'
import { Route as PosHistoryRouteImport } from './routes/pos.history'
import { Route as PosReturnsRouteImport } from './routes/pos.returns'
import { Route as ProFormaIndexRouteImport } from './routes/pro-forma.index'
import { Route as ProFormaProFormaIdRouteImport } from './routes/pro-forma.$proFormaId'
import { Route as ProFormaNewRouteImport } from './routes/pro-forma.new'
import { Route as PurchasingIndexRouteImport } from './routes/purchasing.index'
import { Route as PurchasingPurchaseOrderIdRouteImport } from './routes/purchasing.$purchaseOrderId'
import { Route as PurchasingNewRouteImport } from './routes/purchasing.new'
import { Route as SalesIndexRouteImport } from './routes/sales.index'
import { Route as SalesNewRouteImport } from './routes/sales.new'
import { Route as InventoryProductIdIndexRouteImport } from './routes/inventory.$productId.index'
import { Route as InventoryProductIdEditRouteImport } from './routes/inventory.$productId.edit'
import { Route as PurchasingSuppliersIndexRouteImport } from './routes/purchasing.suppliers.index'
import { Route as PurchasingSuppliersSupplierIdRouteImport } from './routes/purchasing.suppliers.$supplierId'
import { Route as SalesInvoiceIdIndexRouteImport } from './routes/sales.$invoiceId.index'
import { Route as SalesInvoiceIdEditRouteImport } from './routes/sales.$invoiceId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingRoute = AccountingRouteImport.update({
  id: '/accounting',
  path: '/accounting',
  getParentRoute: () => rootRouteImport,
} as any)
const BankingRoute = BankingRouteImport.update({
  id: '/banking',
  path: '/banking',
  getParentRoute: () => rootRouteImport,
} as any)
const EndOfDayRoute = EndOfDayRouteImport.update({
  id: '/end-of-day',
  path: '/end-of-day',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PayrollRoute = PayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const PosRoute = PosRouteImport.update({
  id: '/pos',
  path: '/pos',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingRoute = PurchasingRouteImport.update({
  id: '/purchasing',
  path: '/purchasing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesRoute = SalesRouteImport.update({
  id: '/sales',
  path: '/sales',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountingIndexRoute = AccountingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountingRoute,
} as any)
const AccountingBalanceSheetRoute = AccountingBalanceSheetRouteImport.update({
  id: '/balance-sheet',
  path: '/balance-sheet',
  getParentRoute: () => AccountingRoute,
} as any)
const AccountingCashFlowRoute = AccountingCashFlowRouteImport.update({
  id: '/cash-flow',
  path: '/cash-flow',
  getParentRoute: () => AccountingRoute,
} as any)
const AccountingJournalEntriesRoute =
  AccountingJournalEntriesRouteImport.update({
    id: '/journal-entries',
    path: '/journal-entries',
    getParentRoute: () => AccountingRoute,
  } as any)
const AccountingLedgerRoute = AccountingLedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => AccountingRoute,
} as any)
const AccountingProfitLossRoute = AccountingProfitLossRouteImport.update({
  id: '/profit-loss',
  path: '/profit-loss',
  getParentRoute: () => AccountingRoute,
} as any)
const AccountingTrialBalanceRoute = AccountingTrialBalanceRouteImport.update({
  id: '/trial-balance',
  path: '/trial-balance',
  getParentRoute: () => AccountingRoute,
} as any)
const BankingIndexRoute = BankingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BankingRoute,
} as any)
const BankingHistoryRoute = BankingHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => BankingRoute,
} as any)
const BankingReconcileRoute = BankingReconcileRouteImport.update({
  id: '/reconcile',
  path: '/reconcile',
  getParentRoute: () => BankingRoute,
} as any)
const CustomerDepositsIndexRoute = CustomerDepositsIndexRouteImport.update({
  id: '/customer-deposits/',
  path: '/customer-deposits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDepositsDepositIdRoute =
  CustomerDepositsDepositIdRouteImport.update({
    id: '/customer-deposits/$depositId',
    path: '/customer-deposits/$depositId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdRoute = CustomersCustomerIdRouteImport.update({
  id: '/customers/$customerId',
  path: '/customers/$customerId',
  getParentRoute: () => rootRouteImport,
} as any)
const EndOfDayIndexRoute = EndOfDayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EndOfDayRoute,
} as any)
const EndOfDayDepositsRoute = EndOfDayDepositsRouteImport.update({
  id: '/deposits',
  path: '/deposits',
  getParentRoute: () => EndOfDayRoute,
} as any)
const EndOfDayHistoryRoute = EndOfDayHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => EndOfDayRoute,
} as any)
const ExpensesIndexRoute = ExpensesIndexRouteImport.update({
  id: '/expenses/',
  path: '/expenses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesExpenseIdRoute = ExpensesExpenseIdRouteImport.update({
  id: '/expenses/$expenseId',
  path: '/expenses/$expenseId',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryIndexRoute = InventoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InventoryRoute,
} as any)
const PayrollIndexRoute = PayrollIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollRunIdRoute = PayrollRunIdRouteImport.update({
  id: '/$runId',
  path: '/$runId',
  getParentRoute: () => PayrollRoute,
} as any)
const PayrollPayConfigRoute = PayrollPayConfigRouteImport.update({
  id: '/pay-config',
  path: '/pay-config',
  getParentRoute: () => PayrollRoute,
} as any)
const PayslipsPayslipIdRoute = PayslipsPayslipIdRouteImport.update({
  id: '/payslips/$payslipId',
  path: '/payslips/$payslipId',
  getParentRoute: () => rootRouteImport,
} as any)
const PosIndexRoute = PosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PosRoute,
} as any)
const PosHistoryRoute = PosHistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => PosRoute,
} as any)
const PosReturnsRoute = PosReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => PosRoute,
} as any)
const ProFormaIndexRoute = ProFormaIndexRouteImport.update({
  id: '/pro-forma/',
  path: '/pro-forma/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProFormaProFormaIdRoute = ProFormaProFormaIdRouteImport.update({
  id: '/pro-forma/$proFormaId',
  path: '/pro-forma/$proFormaId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProFormaNewRoute = ProFormaNewRouteImport.update({
  id: '/pro-forma/new',
  path: '/pro-forma/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasingIndexRoute = PurchasingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PurchasingRoute,
} as any)
const PurchasingPurchaseOrderIdRoute =
  PurchasingPurchaseOrderIdRouteImport.update({
    id: '/$purchaseOrderId',
    path: '/$purchaseOrderId',
    getParentRoute: () => PurchasingRoute,
  } as any)
const PurchasingNewRoute = PurchasingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => PurchasingRoute,
} as any)
const SalesIndexRoute = SalesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SalesRoute,
} as any)
const SalesNewRoute = SalesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => SalesRoute,
} as any)
const InventoryProductIdIndexRoute = InventoryProductIdIndexRouteImport.update({
  id: '/$productId/',
  path: '/$productId/',
  getParentRoute: () => InventoryRoute,
} as any)
const InventoryProductIdEditRoute = InventoryProductIdEditRouteImport.update({
  id: '/$productId/edit',
  path: '/$productId/edit',
  getParentRoute: () => InventoryRoute,
} as any)
const PurchasingSuppliersIndexRoute =
  PurchasingSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => PurchasingRoute,
  } as any)
const PurchasingSuppliersSupplierIdRoute =
  PurchasingSuppliersSupplierIdRouteImport.update({
    id: '/suppliers/$supplierId',
    path: '/suppliers/$supplierId',
    getParentRoute: () => PurchasingRoute,
  } as any)
const SalesInvoiceIdIndexRoute = SalesInvoiceIdIndexRouteImport.update({
  id: '/$invoiceId/',
  path: '/$invoiceId/',
  getParentRoute: () => SalesRoute,
} as any)
const SalesInvoiceIdEditRoute = SalesInvoiceIdEditRouteImport.update({
  id: '/$invoiceId/edit',
  path: '/$invoiceId/edit',
  getParentRoute: () => SalesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/accounting': typeof AccountingRouteWithChildren
  '/banking': typeof BankingRouteWithChildren
  '/end-of-day': typeof EndOfDayRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRouteWithChildren
  '/pos': typeof PosRouteWithChildren
  '/purchasing': typeof PurchasingRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/accounting/balance-sheet': typeof AccountingBalanceSheetRoute
  '/accounting/cash-flow': typeof AccountingCashFlowRoute
  '/accounting/journal-entries': typeof AccountingJournalEntriesRoute
  '/accounting/ledger': typeof AccountingLedgerRoute
  '/accounting/profit-loss': typeof AccountingProfitLossRoute
  '/accounting/trial-balance': typeof AccountingTrialBalanceRoute
  '/banking/history': typeof BankingHistoryRoute
  '/banking/reconcile': typeof BankingReconcileRoute
  '/customer-deposits/$depositId': typeof CustomerDepositsDepositIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/end-of-day/deposits': typeof EndOfDayDepositsRoute
  '/end-of-day/history': typeof EndOfDayHistoryRoute
  '/expenses/$expenseId': typeof ExpensesExpenseIdRoute
  '/payroll/$runId': typeof PayrollRunIdRoute
  '/payroll/pay-config': typeof PayrollPayConfigRoute
  '/payslips/$payslipId': typeof PayslipsPayslipIdRoute
  '/pos/history': typeof PosHistoryRoute
  '/pos/returns': typeof PosReturnsRoute
  '/pro-forma/$proFormaId': typeof ProFormaProFormaIdRoute
  '/pro-forma/new': typeof ProFormaNewRoute
  '/purchasing/$purchaseOrderId': typeof PurchasingPurchaseOrderIdRoute
  '/purchasing/new': typeof PurchasingNewRoute
  '/sales/new': typeof SalesNewRoute
  '/accounting/': typeof AccountingIndexRoute
  '/banking/': typeof BankingIndexRoute
  '/customer-deposits/': typeof CustomerDepositsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/end-of-day/': typeof EndOfDayIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/pos/': typeof PosIndexRoute
  '/pro-forma/': typeof ProFormaIndexRoute
  '/purchasing/': typeof PurchasingIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/inventory/$productId/edit': typeof InventoryProductIdEditRoute
  '/purchasing/suppliers/$supplierId': typeof PurchasingSuppliersSupplierIdRoute
  '/sales/$invoiceId/edit': typeof SalesInvoiceIdEditRoute
  '/inventory/$productId/': typeof InventoryProductIdIndexRoute
  '/purchasing/suppliers/': typeof PurchasingSuppliersIndexRoute
  '/sales/$invoiceId/': typeof SalesInvoiceIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/login': typeof LoginRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/accounting/balance-sheet': typeof AccountingBalanceSheetRoute
  '/accounting/cash-flow': typeof AccountingCashFlowRoute
  '/accounting/journal-entries': typeof AccountingJournalEntriesRoute
  '/accounting/ledger': typeof AccountingLedgerRoute
  '/accounting/profit-loss': typeof AccountingProfitLossRoute
  '/accounting/trial-balance': typeof AccountingTrialBalanceRoute
  '/banking/history': typeof BankingHistoryRoute
  '/banking/reconcile': typeof BankingReconcileRoute
  '/customer-deposits/$depositId': typeof CustomerDepositsDepositIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/end-of-day/deposits': typeof EndOfDayDepositsRoute
  '/end-of-day/history': typeof EndOfDayHistoryRoute
  '/expenses/$expenseId': typeof ExpensesExpenseIdRoute
  '/payroll/$runId': typeof PayrollRunIdRoute
  '/payroll/pay-config': typeof PayrollPayConfigRoute
  '/payslips/$payslipId': typeof PayslipsPayslipIdRoute
  '/pos/history': typeof PosHistoryRoute
  '/pos/returns': typeof PosReturnsRoute
  '/pro-forma/$proFormaId': typeof ProFormaProFormaIdRoute
  '/pro-forma/new': typeof ProFormaNewRoute
  '/purchasing/$purchaseOrderId': typeof PurchasingPurchaseOrderIdRoute
  '/purchasing/new': typeof PurchasingNewRoute
  '/sales/new': typeof SalesNewRoute
  '/accounting': typeof AccountingIndexRoute
  '/banking': typeof BankingIndexRoute
  '/customer-deposits': typeof CustomerDepositsIndexRoute
  '/customers': typeof CustomersIndexRoute
  '/end-of-day': typeof EndOfDayIndexRoute
  '/expenses': typeof ExpensesIndexRoute
  '/inventory': typeof InventoryIndexRoute
  '/payroll': typeof PayrollIndexRoute
  '/pos': typeof PosIndexRoute
  '/pro-forma': typeof ProFormaIndexRoute
  '/purchasing': typeof PurchasingIndexRoute
  '/sales': typeof SalesIndexRoute
  '/inventory/$productId/edit': typeof InventoryProductIdEditRoute
  '/purchasing/suppliers/$supplierId': typeof PurchasingSuppliersSupplierIdRoute
  '/sales/$invoiceId/edit': typeof SalesInvoiceIdEditRoute
  '/inventory/$productId': typeof InventoryProductIdIndexRoute
  '/purchasing/suppliers': typeof PurchasingSuppliersIndexRoute
  '/sales/$invoiceId': typeof SalesInvoiceIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/accounting': typeof AccountingRouteWithChildren
  '/banking': typeof BankingRouteWithChildren
  '/end-of-day': typeof EndOfDayRouteWithChildren
  '/inventory': typeof InventoryRouteWithChildren
  '/login': typeof LoginRoute
  '/payroll': typeof PayrollRouteWithChildren
  '/pos': typeof PosRouteWithChildren
  '/purchasing': typeof PurchasingRouteWithChildren
  '/reports': typeof ReportsRoute
  '/sales': typeof SalesRouteWithChildren
  '/settings': typeof SettingsRoute
  '/accounting/balance-sheet': typeof AccountingBalanceSheetRoute
  '/accounting/cash-flow': typeof AccountingCashFlowRoute
  '/accounting/journal-entries': typeof AccountingJournalEntriesRoute
  '/accounting/ledger': typeof AccountingLedgerRoute
  '/accounting/profit-loss': typeof AccountingProfitLossRoute
  '/accounting/trial-balance': typeof AccountingTrialBalanceRoute
  '/banking/history': typeof BankingHistoryRoute
  '/banking/reconcile': typeof BankingReconcileRoute
  '/customer-deposits/$depositId': typeof CustomerDepositsDepositIdRoute
  '/customers/$customerId': typeof CustomersCustomerIdRoute
  '/end-of-day/deposits': typeof EndOfDayDepositsRoute
  '/end-of-day/history': typeof EndOfDayHistoryRoute
  '/expenses/$expenseId': typeof ExpensesExpenseIdRoute
  '/payroll/$runId': typeof PayrollRunIdRoute
  '/payroll/pay-config': typeof PayrollPayConfigRoute
  '/payslips/$payslipId': typeof PayslipsPayslipIdRoute
  '/pos/history': typeof PosHistoryRoute
  '/pos/returns': typeof PosReturnsRoute
  '/pro-forma/$proFormaId': typeof ProFormaProFormaIdRoute
  '/pro-forma/new': typeof ProFormaNewRoute
  '/purchasing/$purchaseOrderId': typeof PurchasingPurchaseOrderIdRoute
  '/purchasing/new': typeof PurchasingNewRoute
  '/sales/new': typeof SalesNewRoute
  '/accounting/': typeof AccountingIndexRoute
  '/banking/': typeof BankingIndexRoute
  '/customer-deposits/': typeof CustomerDepositsIndexRoute
  '/customers/': typeof CustomersIndexRoute
  '/end-of-day/': typeof EndOfDayIndexRoute
  '/expenses/': typeof ExpensesIndexRoute
  '/inventory/': typeof InventoryIndexRoute
  '/payroll/': typeof PayrollIndexRoute
  '/pos/': typeof PosIndexRoute
  '/pro-forma/': typeof ProFormaIndexRoute
  '/purchasing/': typeof PurchasingIndexRoute
  '/sales/': typeof SalesIndexRoute
  '/inventory/$productId/edit': typeof InventoryProductIdEditRoute
  '/purchasing/suppliers/$supplierId': typeof PurchasingSuppliersSupplierIdRoute
  '/sales/$invoiceId/edit': typeof SalesInvoiceIdEditRoute
  '/inventory/$productId/': typeof InventoryProductIdIndexRoute
  '/purchasing/suppliers/': typeof PurchasingSuppliersIndexRoute
  '/sales/$invoiceId/': typeof SalesInvoiceIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/accounting'
    | '/banking'
    | '/end-of-day'
    | '/inventory'
    | '/login'
    | '/payroll'
    | '/pos'
    | '/purchasing'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/accounting/balance-sheet'
    | '/accounting/cash-flow'
    | '/accounting/journal-entries'
    | '/accounting/ledger'
    | '/accounting/profit-loss'
    | '/accounting/trial-balance'
    | '/banking/history'
    | '/banking/reconcile'
    | '/customer-deposits/$depositId'
    | '/customers/$customerId'
    | '/end-of-day/deposits'
    | '/end-of-day/history'
    | '/expenses/$expenseId'
    | '/payroll/$runId'
    | '/payroll/pay-config'
    | '/payslips/$payslipId'
    | '/pos/history'
    | '/pos/returns'
    | '/pro-forma/$proFormaId'
    | '/pro-forma/new'
    | '/purchasing/$purchaseOrderId'
    | '/purchasing/new'
    | '/sales/new'
    | '/accounting/'
    | '/banking/'
    | '/customer-deposits/'
    | '/customers/'
    | '/end-of-day/'
    | '/expenses/'
    | '/inventory/'
    | '/payroll/'
    | '/pos/'
    | '/pro-forma/'
    | '/purchasing/'
    | '/sales/'
    | '/inventory/$productId/edit'
    | '/purchasing/suppliers/$supplierId'
    | '/sales/$invoiceId/edit'
    | '/inventory/$productId/'
    | '/purchasing/suppliers/'
    | '/sales/$invoiceId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invite'
    | '/login'
    | '/reports'
    | '/settings'
    | '/accounting/balance-sheet'
    | '/accounting/cash-flow'
    | '/accounting/journal-entries'
    | '/accounting/ledger'
    | '/accounting/profit-loss'
    | '/accounting/trial-balance'
    | '/banking/history'
    | '/banking/reconcile'
    | '/customer-deposits/$depositId'
    | '/customers/$customerId'
    | '/end-of-day/deposits'
    | '/end-of-day/history'
    | '/expenses/$expenseId'
    | '/payroll/$runId'
    | '/payroll/pay-config'
    | '/payslips/$payslipId'
    | '/pos/history'
    | '/pos/returns'
    | '/pro-forma/$proFormaId'
    | '/pro-forma/new'
    | '/purchasing/$purchaseOrderId'
    | '/purchasing/new'
    | '/sales/new'
    | '/accounting'
    | '/banking'
    | '/customer-deposits'
    | '/customers'
    | '/end-of-day'
    | '/expenses'
    | '/inventory'
    | '/payroll'
    | '/pos'
    | '/pro-forma'
    | '/purchasing'
    | '/sales'
    | '/inventory/$productId/edit'
    | '/purchasing/suppliers/$supplierId'
    | '/sales/$invoiceId/edit'
    | '/inventory/$productId'
    | '/purchasing/suppliers'
    | '/sales/$invoiceId'
  id:
    | '__root__'
    | '/'
    | '/accept-invite'
    | '/accounting'
    | '/banking'
    | '/end-of-day'
    | '/inventory'
    | '/login'
    | '/payroll'
    | '/pos'
    | '/purchasing'
    | '/reports'
    | '/sales'
    | '/settings'
    | '/accounting/balance-sheet'
    | '/accounting/cash-flow'
    | '/accounting/journal-entries'
    | '/accounting/ledger'
    | '/accounting/profit-loss'
    | '/accounting/trial-balance'
    | '/banking/history'
    | '/banking/reconcile'
    | '/customer-deposits/$depositId'
    | '/customers/$customerId'
    | '/end-of-day/deposits'
    | '/end-of-day/history'
    | '/expenses/$expenseId'
    | '/payroll/$runId'
    | '/payroll/pay-config'
    | '/payslips/$payslipId'
    | '/pos/history'
    | '/pos/returns'
    | '/pro-forma/$proFormaId'
    | '/pro-forma/new'
    | '/purchasing/$purchaseOrderId'
    | '/purchasing/new'
    | '/sales/new'
    | '/accounting/'
    | '/banking/'
    | '/customer-deposits/'
    | '/customers/'
    | '/end-of-day/'
    | '/expenses/'
    | '/inventory/'
    | '/payroll/'
    | '/pos/'
    | '/pro-forma/'
    | '/purchasing/'
    | '/sales/'
    | '/inventory/$productId/edit'
    | '/purchasing/suppliers/$supplierId'
    | '/sales/$invoiceId/edit'
    | '/inventory/$productId/'
    | '/purchasing/suppliers/'
    | '/sales/$invoiceId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInviteRoute: typeof AcceptInviteRoute
  AccountingRoute: typeof AccountingRouteWithChildren
  BankingRoute: typeof BankingRouteWithChildren
  EndOfDayRoute: typeof EndOfDayRouteWithChildren
  InventoryRoute: typeof InventoryRouteWithChildren
  LoginRoute: typeof LoginRoute
  PayrollRoute: typeof PayrollRouteWithChildren
  PosRoute: typeof PosRouteWithChildren
  PurchasingRoute: typeof PurchasingRouteWithChildren
  ReportsRoute: typeof ReportsRoute
  SalesRoute: typeof SalesRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  CustomerDepositsDepositIdRoute: typeof CustomerDepositsDepositIdRoute
  CustomersCustomerIdRoute: typeof CustomersCustomerIdRoute
  ExpensesExpenseIdRoute: typeof ExpensesExpenseIdRoute
  PayslipsPayslipIdRoute: typeof PayslipsPayslipIdRoute
  ProFormaProFormaIdRoute: typeof ProFormaProFormaIdRoute
  ProFormaNewRoute: typeof ProFormaNewRoute
  CustomerDepositsIndexRoute: typeof CustomerDepositsIndexRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  ExpensesIndexRoute: typeof ExpensesIndexRoute
  ProFormaIndexRoute: typeof ProFormaIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting': {
      id: '/accounting'
      path: '/accounting'
      fullPath: '/accounting'
      preLoaderRoute: typeof AccountingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banking': {
      id: '/banking'
      path: '/banking'
      fullPath: '/banking'
      preLoaderRoute: typeof BankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/end-of-day': {
      id: '/end-of-day'
      path: '/end-of-day'
      fullPath: '/end-of-day'
      preLoaderRoute: typeof EndOfDayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payroll': {
      id: '/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof PayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos': {
      id: '/pos'
      path: '/pos'
      fullPath: '/pos'
      preLoaderRoute: typeof PosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing': {
      id: '/purchasing'
      path: '/purchasing'
      fullPath: '/purchasing'
      preLoaderRoute: typeof PurchasingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales': {
      id: '/sales'
      path: '/sales'
      fullPath: '/sales'
      preLoaderRoute: typeof SalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounting/': {
      id: '/accounting/'
      path: '/'
      fullPath: '/accounting/'
      preLoaderRoute: typeof AccountingIndexRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/balance-sheet': {
      id: '/accounting/balance-sheet'
      path: '/balance-sheet'
      fullPath: '/accounting/balance-sheet'
      preLoaderRoute: typeof AccountingBalanceSheetRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/cash-flow': {
      id: '/accounting/cash-flow'
      path: '/cash-flow'
      fullPath: '/accounting/cash-flow'
      preLoaderRoute: typeof AccountingCashFlowRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/journal-entries': {
      id: '/accounting/journal-entries'
      path: '/journal-entries'
      fullPath: '/accounting/journal-entries'
      preLoaderRoute: typeof AccountingJournalEntriesRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/ledger': {
      id: '/accounting/ledger'
      path: '/ledger'
      fullPath: '/accounting/ledger'
      preLoaderRoute: typeof AccountingLedgerRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/profit-loss': {
      id: '/accounting/profit-loss'
      path: '/profit-loss'
      fullPath: '/accounting/profit-loss'
      preLoaderRoute: typeof AccountingProfitLossRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/accounting/trial-balance': {
      id: '/accounting/trial-balance'
      path: '/trial-balance'
      fullPath: '/accounting/trial-balance'
      preLoaderRoute: typeof AccountingTrialBalanceRouteImport
      parentRoute: typeof AccountingRoute
    }
    '/banking/': {
      id: '/banking/'
      path: '/'
      fullPath: '/banking/'
      preLoaderRoute: typeof BankingIndexRouteImport
      parentRoute: typeof BankingRoute
    }
    '/banking/history': {
      id: '/banking/history'
      path: '/history'
      fullPath: '/banking/history'
      preLoaderRoute: typeof BankingHistoryRouteImport
      parentRoute: typeof BankingRoute
    }
    '/banking/reconcile': {
      id: '/banking/reconcile'
      path: '/reconcile'
      fullPath: '/banking/reconcile'
      preLoaderRoute: typeof BankingReconcileRouteImport
      parentRoute: typeof BankingRoute
    }
    '/customer-deposits/': {
      id: '/customer-deposits/'
      path: '/customer-deposits'
      fullPath: '/customer-deposits/'
      preLoaderRoute: typeof CustomerDepositsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-deposits/$depositId': {
      id: '/customer-deposits/$depositId'
      path: '/customer-deposits/$depositId'
      fullPath: '/customer-deposits/$depositId'
      preLoaderRoute: typeof CustomerDepositsDepositIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId': {
      id: '/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof CustomersCustomerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/end-of-day/': {
      id: '/end-of-day/'
      path: '/'
      fullPath: '/end-of-day/'
      preLoaderRoute: typeof EndOfDayIndexRouteImport
      parentRoute: typeof EndOfDayRoute
    }
    '/end-of-day/deposits': {
      id: '/end-of-day/deposits'
      path: '/deposits'
      fullPath: '/end-of-day/deposits'
      preLoaderRoute: typeof EndOfDayDepositsRouteImport
      parentRoute: typeof EndOfDayRoute
    }
    '/end-of-day/history': {
      id: '/end-of-day/history'
      path: '/history'
      fullPath: '/end-of-day/history'
      preLoaderRoute: typeof EndOfDayHistoryRouteImport
      parentRoute: typeof EndOfDayRoute
    }
    '/expenses/': {
      id: '/expenses/'
      path: '/expenses'
      fullPath: '/expenses/'
      preLoaderRoute: typeof ExpensesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses/$expenseId': {
      id: '/expenses/$expenseId'
      path: '/expenses/$expenseId'
      fullPath: '/expenses/$expenseId'
      preLoaderRoute: typeof ExpensesExpenseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory/': {
      id: '/inventory/'
      path: '/'
      fullPath: '/inventory/'
      preLoaderRoute: typeof InventoryIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/payroll/': {
      id: '/payroll/'
      path: '/'
      fullPath: '/payroll/'
      preLoaderRoute: typeof PayrollIndexRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/$runId': {
      id: '/payroll/$runId'
      path: '/$runId'
      fullPath: '/payroll/$runId'
      preLoaderRoute: typeof PayrollRunIdRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payroll/pay-config': {
      id: '/payroll/pay-config'
      path: '/pay-config'
      fullPath: '/payroll/pay-config'
      preLoaderRoute: typeof PayrollPayConfigRouteImport
      parentRoute: typeof PayrollRoute
    }
    '/payslips/$payslipId': {
      id: '/payslips/$payslipId'
      path: '/payslips/$payslipId'
      fullPath: '/payslips/$payslipId'
      preLoaderRoute: typeof PayslipsPayslipIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pos/': {
      id: '/pos/'
      path: '/'
      fullPath: '/pos/'
      preLoaderRoute: typeof PosIndexRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/history': {
      id: '/pos/history'
      path: '/history'
      fullPath: '/pos/history'
      preLoaderRoute: typeof PosHistoryRouteImport
      parentRoute: typeof PosRoute
    }
    '/pos/returns': {
      id: '/pos/returns'
      path: '/returns'
      fullPath: '/pos/returns'
      preLoaderRoute: typeof PosReturnsRouteImport
      parentRoute: typeof PosRoute
    }
    '/pro-forma/': {
      id: '/pro-forma/'
      path: '/pro-forma'
      fullPath: '/pro-forma/'
      preLoaderRoute: typeof ProFormaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-forma/$proFormaId': {
      id: '/pro-forma/$proFormaId'
      path: '/pro-forma/$proFormaId'
      fullPath: '/pro-forma/$proFormaId'
      preLoaderRoute: typeof ProFormaProFormaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro-forma/new': {
      id: '/pro-forma/new'
      path: '/pro-forma/new'
      fullPath: '/pro-forma/new'
      preLoaderRoute: typeof ProFormaNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchasing/': {
      id: '/purchasing/'
      path: '/'
      fullPath: '/purchasing/'
      preLoaderRoute: typeof PurchasingIndexRouteImport
      parentRoute: typeof PurchasingRoute
    }
    '/purchasing/$purchaseOrderId': {
      id: '/purchasing/$purchaseOrderId'
      path: '/$purchaseOrderId'
      fullPath: '/purchasing/$purchaseOrderId'
      preLoaderRoute: typeof PurchasingPurchaseOrderIdRouteImport
      parentRoute: typeof PurchasingRoute
    }
    '/purchasing/new': {
      id: '/purchasing/new'
      path: '/new'
      fullPath: '/purchasing/new'
      preLoaderRoute: typeof PurchasingNewRouteImport
      parentRoute: typeof PurchasingRoute
    }
    '/sales/': {
      id: '/sales/'
      path: '/'
      fullPath: '/sales/'
      preLoaderRoute: typeof SalesIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/new': {
      id: '/sales/new'
      path: '/new'
      fullPath: '/sales/new'
      preLoaderRoute: typeof SalesNewRouteImport
      parentRoute: typeof SalesRoute
    }
    '/inventory/$productId/': {
      id: '/inventory/$productId/'
      path: '/$productId'
      fullPath: '/inventory/$productId/'
      preLoaderRoute: typeof InventoryProductIdIndexRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/inventory/$productId/edit': {
      id: '/inventory/$productId/edit'
      path: '/$productId/edit'
      fullPath: '/inventory/$productId/edit'
      preLoaderRoute: typeof InventoryProductIdEditRouteImport
      parentRoute: typeof InventoryRoute
    }
    '/purchasing/suppliers/': {
      id: '/purchasing/suppliers/'
      path: '/suppliers'
      fullPath: '/purchasing/suppliers/'
      preLoaderRoute: typeof PurchasingSuppliersIndexRouteImport
      parentRoute: typeof PurchasingRoute
    }
    '/purchasing/suppliers/$supplierId': {
      id: '/purchasing/suppliers/$supplierId'
      path: '/suppliers/$supplierId'
      fullPath: '/purchasing/suppliers/$supplierId'
      preLoaderRoute: typeof PurchasingSuppliersSupplierIdRouteImport
      parentRoute: typeof PurchasingRoute
    }
    '/sales/$invoiceId/': {
      id: '/sales/$invoiceId/'
      path: '/$invoiceId'
      fullPath: '/sales/$invoiceId/'
      preLoaderRoute: typeof SalesInvoiceIdIndexRouteImport
      parentRoute: typeof SalesRoute
    }
    '/sales/$invoiceId/edit': {
      id: '/sales/$invoiceId/edit'
      path: '/$invoiceId/edit'
      fullPath: '/sales/$invoiceId/edit'
      preLoaderRoute: typeof SalesInvoiceIdEditRouteImport
      parentRoute: typeof SalesRoute
    }
  }
}

interface AccountingRouteChildren {
  AccountingBalanceSheetRoute: typeof AccountingBalanceSheetRoute
  AccountingCashFlowRoute: typeof AccountingCashFlowRoute
  AccountingJournalEntriesRoute: typeof AccountingJournalEntriesRoute
  AccountingLedgerRoute: typeof AccountingLedgerRoute
  AccountingProfitLossRoute: typeof AccountingProfitLossRoute
  AccountingTrialBalanceRoute: typeof AccountingTrialBalanceRoute
  AccountingIndexRoute: typeof AccountingIndexRoute
}

const AccountingRouteChildren: AccountingRouteChildren = {
  AccountingBalanceSheetRoute: AccountingBalanceSheetRoute,
  AccountingCashFlowRoute: AccountingCashFlowRoute,
  AccountingJournalEntriesRoute: AccountingJournalEntriesRoute,
  AccountingLedgerRoute: AccountingLedgerRoute,
  AccountingProfitLossRoute: AccountingProfitLossRoute,
  AccountingTrialBalanceRoute: AccountingTrialBalanceRoute,
  AccountingIndexRoute: AccountingIndexRoute,
}

const AccountingRouteWithChildren = AccountingRoute._addFileChildren(
  AccountingRouteChildren,
)

interface BankingRouteChildren {
  BankingHistoryRoute: typeof BankingHistoryRoute
  BankingReconcileRoute: typeof BankingReconcileRoute
  BankingIndexRoute: typeof BankingIndexRoute
}

const BankingRouteChildren: BankingRouteChildren = {
  BankingHistoryRoute: BankingHistoryRoute,
  BankingReconcileRoute: BankingReconcileRoute,
  BankingIndexRoute: BankingIndexRoute,
}

const BankingRouteWithChildren =
  BankingRoute._addFileChildren(BankingRouteChildren)

interface EndOfDayRouteChildren {
  EndOfDayDepositsRoute: typeof EndOfDayDepositsRoute
  EndOfDayHistoryRoute: typeof EndOfDayHistoryRoute
  EndOfDayIndexRoute: typeof EndOfDayIndexRoute
}

const EndOfDayRouteChildren: EndOfDayRouteChildren = {
  EndOfDayDepositsRoute: EndOfDayDepositsRoute,
  EndOfDayHistoryRoute: EndOfDayHistoryRoute,
  EndOfDayIndexRoute: EndOfDayIndexRoute,
}

const EndOfDayRouteWithChildren = EndOfDayRoute._addFileChildren(
  EndOfDayRouteChildren,
)

interface InventoryRouteChildren {
  InventoryIndexRoute: typeof InventoryIndexRoute
  InventoryProductIdEditRoute: typeof InventoryProductIdEditRoute
  InventoryProductIdIndexRoute: typeof InventoryProductIdIndexRoute
}

const InventoryRouteChildren: InventoryRouteChildren = {
  InventoryIndexRoute: InventoryIndexRoute,
  InventoryProductIdEditRoute: InventoryProductIdEditRoute,
  InventoryProductIdIndexRoute: InventoryProductIdIndexRoute,
}

const InventoryRouteWithChildren = InventoryRoute._addFileChildren(
  InventoryRouteChildren,
)

interface PayrollRouteChildren {
  PayrollRunIdRoute: typeof PayrollRunIdRoute
  PayrollPayConfigRoute: typeof PayrollPayConfigRoute
  PayrollIndexRoute: typeof PayrollIndexRoute
}

const PayrollRouteChildren: PayrollRouteChildren = {
  PayrollRunIdRoute: PayrollRunIdRoute,
  PayrollPayConfigRoute: PayrollPayConfigRoute,
  PayrollIndexRoute: PayrollIndexRoute,
}

const PayrollRouteWithChildren =
  PayrollRoute._addFileChildren(PayrollRouteChildren)

interface PosRouteChildren {
  PosHistoryRoute: typeof PosHistoryRoute
  PosReturnsRoute: typeof PosReturnsRoute
  PosIndexRoute: typeof PosIndexRoute
}

const PosRouteChildren: PosRouteChildren = {
  PosHistoryRoute: PosHistoryRoute,
  PosReturnsRoute: PosReturnsRoute,
  PosIndexRoute: PosIndexRoute,
}

const PosRouteWithChildren = PosRoute._addFileChildren(PosRouteChildren)

interface PurchasingRouteChildren {
  PurchasingPurchaseOrderIdRoute: typeof PurchasingPurchaseOrderIdRoute
  PurchasingNewRoute: typeof PurchasingNewRoute
  PurchasingIndexRoute: typeof PurchasingIndexRoute
  PurchasingSuppliersSupplierIdRoute: typeof PurchasingSuppliersSupplierIdRoute
  PurchasingSuppliersIndexRoute: typeof PurchasingSuppliersIndexRoute
}

const PurchasingRouteChildren: PurchasingRouteChildren = {
  PurchasingPurchaseOrderIdRoute: PurchasingPurchaseOrderIdRoute,
  PurchasingNewRoute: PurchasingNewRoute,
  PurchasingIndexRoute: PurchasingIndexRoute,
  PurchasingSuppliersSupplierIdRoute: PurchasingSuppliersSupplierIdRoute,
  PurchasingSuppliersIndexRoute: PurchasingSuppliersIndexRoute,
}

const PurchasingRouteWithChildren = PurchasingRoute._addFileChildren(
  PurchasingRouteChildren,
)

interface SalesRouteChildren {
  SalesNewRoute: typeof SalesNewRoute
  SalesIndexRoute: typeof SalesIndexRoute
  SalesInvoiceIdEditRoute: typeof SalesInvoiceIdEditRoute
  SalesInvoiceIdIndexRoute: typeof SalesInvoiceIdIndexRoute
}

const SalesRouteChildren: SalesRouteChildren = {
  SalesNewRoute: SalesNewRoute,
  SalesIndexRoute: SalesIndexRoute,
  SalesInvoiceIdEditRoute: SalesInvoiceIdEditRoute,
  SalesInvoiceIdIndexRoute: SalesInvoiceIdIndexRoute,
}

const SalesRouteWithChildren = SalesRoute._addFileChildren(SalesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInviteRoute: AcceptInviteRoute,
  AccountingRoute: AccountingRouteWithChildren,
  BankingRoute: BankingRouteWithChildren,
  EndOfDayRoute: EndOfDayRouteWithChildren,
  InventoryRoute: InventoryRouteWithChildren,
  LoginRoute: LoginRoute,
  PayrollRoute: PayrollRouteWithChildren,
  PosRoute: PosRouteWithChildren,
  PurchasingRoute: PurchasingRouteWithChildren,
  ReportsRoute: ReportsRoute,
  SalesRoute: SalesRouteWithChildren,
  SettingsRoute: SettingsRoute,
  CustomerDepositsDepositIdRoute: CustomerDepositsDepositIdRoute,
  CustomersCustomerIdRoute: CustomersCustomerIdRoute,
  ExpensesExpenseIdRoute: ExpensesExpenseIdRoute,
  PayslipsPayslipIdRoute: PayslipsPayslipIdRoute,
  ProFormaProFormaIdRoute: ProFormaProFormaIdRoute,
  ProFormaNewRoute: ProFormaNewRoute,
  CustomerDepositsIndexRoute: CustomerDepositsIndexRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  ExpensesIndexRoute: ExpensesIndexRoute,
  ProFormaIndexRoute: ProFormaIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
